// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(InventarioContext))]
    partial class InventarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Entities.Estado", b =>
                {
                    b.Property<string>("codEstado")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombreEstado")
                        .HasColumnType("longtext");

                    b.HasKey("codEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Core.Entities.Pais", b =>
                {
                    b.Property<string>("codPais")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombrePais")
                        .HasColumnType("longtext");

                    b.HasKey("codPais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Core.Entities.Region", b =>
                {
                    b.Property<string>("codRegion")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombreRegion")
                        .HasColumnType("longtext");

                    b.HasKey("codRegion");

                    b.ToTable("Regiones");
                });
#pragma warning restore 612, 618
        }
    }
}
